_base_: './lane_line1k_6class.yml'

batch_size: 20
iters: 30000
# iters: 2000

model:
  type: DeepLabV3P
  backbone:
    type: ResNet50_vd
    output_stride: 8
    multi_grid: [1, 2, 4]
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz

  backbone_indices: [0, 3]
  num_classes: 7
  aspp_ratios: [1, 12, 24, 36]
  aspp_out_channels: 256
  align_corners: False
  pretrained: null
  # pretrained: ./models/ade20k/paddle/3_class_pretrained_model.pdparams
