batch_size: 2
iters: 10000

train_dataset:
  type: Dataset
  dataset_root: data/skyimg1.0
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train
  train_path: data/skyimg1.0/train.txt
  num_classes: 4


val_dataset:
  type: Dataset
  dataset_root: data/skyimg1.0
  transforms:
    - type: Normalize
  mode: val
  val_path: data/skyimg1.0/val.txt
  num_classes: 4



optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
